# pipeline suggested name: MANUALLY build apps
# for master or develop branch

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../templates/var_env.yml

stages:
  - stage: validate_build
    displayName: validate all and build all
    condition: ne(variables['ENV'], 'feat')
    jobs:
      - job: lint_all
        displayName: nx lint all apps
        steps:
          - template: ../templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-all.js lint
            displayName: running lint all

      - job: test_all
        displayName: nx test all apps
        steps:
          - template: ../templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-all.js test
            displayName: running test all

      - job: build_all
        displayName: nx build all apps
        dependsOn:
          - lint_all
          - test_all
        condition: |
          and(
            succeeded('lint_all'),
            succeeded('test_all')
          )
        steps:
          - template: ../templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-all.js build $(ENV)
            displayName: running build all
          - publish: $(System.DefaultWorkingDirectory)/dist/apps
            artifact: apps

  - stage: git_push
    displayName: git push
    dependsOn: validate_build
    condition: succeeded()
    jobs:
      - job: push_all
        displayName: push the builded apps
        steps:
          - checkout: self
            persistCredentials: true
            clean: true
          - download: current
            artifact: apps
          - script: |
              cd $(Pipeline.Workspace)/apps
              ls
            displayName: list apps available on $(Pipeline.Workspace)/apps
          - template: ../templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/git-push-builds-to-branches.js $(Pipeline.Workspace)/apps $(ENV)
            displayName: running git push
