# pipeline suggested name: MANUALLY build apps
# for master or develop branch

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: ../templates/var_env.yml

stages:
  - stage: validate_build
    displayName: validate all and build all
    condition: ne(variables['ENV'], 'feat')
    jobs:
      - job: node_deps
        displayName: cache node dependencies
        steps:
          - template: ../templates/steps_install-node-modules.yml

      - job: lint_all
        displayName: nx lint all apps
        dependsOn: node_deps
        condition: succeeded()
        steps:
          - template: ../templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-all.js lint
            displayName: running lint all

      - job: test_all
        displayName: nx test all apps
        dependsOn: node_deps
        condition: succeeded()
        steps:
          - template: ../templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-all.js test
            displayName: running test all
          - template: ../templates/steps_publish-test-results.yml

      - job: build_all
        displayName: nx build all apps
        dependsOn:
          - lint_all
          - test_all
        condition: |
          and(
            succeeded('lint_all'),
            succeeded('test_all')
          )
        steps:
          - template: ../templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-all.js build $(ENV)
            displayName: running build all
          - template: ../templates/steps_apps-artifact_publish.yml

  - stage: git_push
    displayName: git push
    dependsOn: validate_build
    condition: succeeded()
    jobs:
      - job: push_all
        displayName: push the builded apps
        steps:
          - checkout: self
            persistCredentials: true
            clean: true
          - template: ../templates/steps_apps-artifact_download.yml
          - template: ../templates/steps_install-node-modules.yml
          - template: ../templates/steps_download-github-pat.yml
          - script: node ./tools/scripts/git-push-apps-builds-to-branches.js $(ENV) $(Pipeline.Workspace)/apps $(cat $(githubPat.secureFilePath))
            displayName: running git push
