parameters:
  - name: jobName
    type: string
  - name: dependsOn
    type: string
  - name: commandsStr
    type: string
  - name: target
    type: string
  - name: isProdBuild
    type: string
    default: false

jobs:
  - job: ${{ parameters.jobName }}
    displayName: nx run many - ${{ parameters.target }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: |
      and(
        succeeded(),
        not(
          contains(
            parameters.commandsStr,
            '"${{ parameters.target }}":[]'
          )
        )
      )
    variables:
      commandsStr: ${{ parameters.commandsStr }}
      target: ${{ parameters.target }}
      env: 'development'
      ${{ if eq(parameters.isProdBuild, 'true') }}:
        env: 'production'
    steps:
      - template: steps_install-node-modules.yml
      - script: node ./tools/scripts/nx-run-many.js '$(commandsStr)' $(target) $(env)
