parameters:
  - name: nodeVersion
    type: string
    default: '12.x'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.nodeVersion }}
    displayName: 'Install Node.js'

  - template: steps_cache-npm.yml
