steps:
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
        npm
      path: $(Pipeline.Workspace)/.npm
    displayName: Cache npm

  - script: npm ci
