# https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#nodejsnpm
steps:
  - script: echo $(Pipeline.Workspace)

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
        npm
      path: $(Pipeline.Workspace)/.npm
      cacheHitVar: CACHE_RESTORED
    displayName: Cache npm

  - script: |
      npm ci
    condition: ne(variables.CACHE_RESTORED, 'true')
