# Pipeline caching
# https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching
#
steps:
  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
        npm
      path: node_modules
      cacheHitVar: CACHE_RESTORED
    displayName: Cache node_modules

  - script: npm ci
    condition: ne(variables.CACHE_RESTORED, 'true')
    displayName: Install dependencies only if there is no cache available
