# based on:
# Publishing GitHub Pages from Azure Pipelines
# https://cloudblogs.microsoft.com/opensource/2019/04/05/publishing-github-pages-from-azure-pipelines/
#
# Download Secure File task
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-secure-file
#
steps:
  - task: DownloadSecureFile@1
    name: deployKey
    inputs:
      secureFile: deploy_key
    displayName: 'Get the deploy key'

  - script: |
      echo 'Installing deployment key'
      mkdir ~/.ssh
      chmod 700 ~/.ssh

      mv $(deployKey.secureFilePath) ~/.ssh/deploy_key
      chmod 600 ~/.ssh/deploy_key

      echo 'add the deployment key to the ssh'
      ssh-add ~/.ssh/deploy_key

      echo 'ssh-keyscan'
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      echo 'check github authentication'
      ssh -T git@github.com
    displayName: 'Configure to use the deploy key'
