variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    ENV: 'prod'
  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
      ENV: 'uat'
    ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
      ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
        ENV: 'dev'
      ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
        ENV: 'feat'
