# pipeline suggested name: CI pull requests
# validate the pull requests

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger: none
pr:
  branches:
    include:
      - develop
  paths:
    exclude:
      - .azure-pipelines/*
      - .vscode/*
      - tools/*
      - docs/*
      - README.md

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: check_format
    displayName: nx format:check
    steps:
      - template: ../templates/steps_install-node-modules.yml
      - script: |
          npx nx format:check --base=origin/develop --head=HEAD
        displayName: running check

  - job: initial_setup
    displayName: nx calculate commandas
    dependsOn: check_format
    condition: succeeded()
    steps:
      - template: ../templates/steps_install-node-modules.yml
      - script: |
          echo "##vso[task.setvariable variable=COMMANDS;isOutput=true]$(node ./tools/scripts/nx-calculate-commands.js merge)"
        name: setCommands
      - script: echo $(setCommands.COMMANDS)
        name: echoCommands

  - job: lint
    displayName: lint projects
    dependsOn: initial_setup
    condition: |
      and(
        succeeded(),
        not(
          contains(
            dependencies.initial_setup.outputs['setCommands.COMMANDS'],
            '"lint":[]'
          )
        )
      )
    variables:
      COMMANDS: $[ dependencies.initial_setup.outputs['setCommands.COMMANDS'] ]
    steps:
      - template: ../templates/steps_install-node-modules.yml
      - script: node ./tools/scripts/nx-run-many.js '$(COMMANDS)' lint
        displayName: running lint

  - job: test
    displayName: test projects
    dependsOn:
      - initial_setup
      - lint
    condition: |
      and(
        succeeded(),
        not(
          contains(
            dependencies.initial_setup.outputs['setCommands.COMMANDS'],
            '"test":[]'
          )
        )
      )
    variables:
      COMMANDS: $[ dependencies.initial_setup.outputs['setCommands.COMMANDS'] ]
    steps:
      - template: ../templates/steps_install-node-modules.yml
      - script: node ./tools/scripts/nx-run-many.js '$(COMMANDS)' test
        displayName: running tests
      - template: ../templates/steps_publish-test-results.yml

  - job: build_storybook
    displayName: build the affected storybook
    dependsOn:
      - initial_setup
      - test
    condition: |
      and(
        succeeded(),
        not(
          contains(
            dependencies.initial_setup.outputs['setCommands.COMMANDS'],
            '"build-storybook":[]'
          )
        )
      )
    variables:
      COMMANDS: $[ dependencies.initial_setup.outputs['setCommands.COMMANDS'] ]
    steps:
      - template: ../templates/steps_install-node-modules.yml
      - script: node ./tools/scripts/nx-run-many.js '$(COMMANDS)' build-storybook
        displayName: running build storybook

  - job: build
    displayName: build projects
    dependsOn:
      - initial_setup
      - test
    condition: |
      and(
        succeeded(),
        not(
          contains(
            dependencies.initial_setup.outputs['setCommands.COMMANDS'],
            '"build":[]'
          )
        )
      )
    variables:
      COMMANDS: $[ dependencies.initial_setup.outputs['setCommands.COMMANDS'] ]
    steps:
      - template: ../templates/steps_install-node-modules.yml
      - script: node ./tools/scripts/nx-run-many.js '$(COMMANDS)' build
        displayName: running builds
