# Azure CLI task
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops
#
# deploy a static web site to the MS Azure Cloud Storage and CDN
#
# configurations defined as a variable group
#
steps:
  - checkout: self
    clean: true

  - script: |
      echo ''
      echo 'pwd'
      pwd
      echo ''
      echo 'project directory'
      echo ''
      ls -a
      echo ''
      echo 'dist directory'
      echo ''
      cd dist
      ls -a
      echo ''
    displayName: list repository files

  - script: |
      echo 'DEBUG variables values'
      echo 'STATUS: $(STATUS)'
      echo 'azureSubscriptionID: $(azureSubscriptionID)'
      echo 'azureSubscriptionResource: $(azureSubscriptionResource)'
      echo 'azureStorageName: $(azureStorageName)'
      echo 'azureResourceGroupName: $(azureResourceGroupName)'
      echo 'azureCdnEndpointName: $(azureCdnEndpointName)'
      echo 'azureCdnProfileName: $(azureCdnProfileName)'
    displayName: DEBUG variables values
    condition: ne(variables['STATUS'], 'active')

  - task: AzureCLI@1
    displayName: Copy files to Azure Blob storage
    condition: |
      and(
        eq(variables['STATUS'], 'active'),
        ne(variables.azureSubscriptionResource, ''),
        ne(variables.azureStorageName, '')
      )
    inputs:
      azureSubscription: $(azureSubscriptionResource)
      scriptLocation: inlineScript
      inlineScript: |
        az storage blob upload-batch -s "$(System.DefaultWorkingDirectory)/dist" -d \$web --account-name "$(azureStorageName)"

  - task: AzureCLI@1
    displayName: Purge Azure CDN
    condition: |
      and(
        eq(variables['STATUS'], 'active'),
        ne(variables.azureSubscriptionResource, ''),
        ne(variables.azureResourceGroupName, ''),
        ne(variables.azureCdnEndpointName, ''),
        ne(variables.azureCdnProfileName, '')
      )
    inputs:
      azureSubscription: $(azureSubscriptionResource)
      scriptLocation: inlineScript
      inlineScript: |
        az cdn endpoint purge --resource-group $(azureResourceGroupName) --name $(azureCdnEndpointName) --profile-name $(azureCdnProfileName) --content-paths "/*"
