# Azure CLI task
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops
#
# deploy a static web site to the MS Azure Cloud Storage and CDN
#
# configurations defined as a variable group
#
steps:
  - checkout: self
    clean: true
  - script: |
      echo ''
      echo 'project directory'
      echo ''
      ls -a
      echo ''
      echo 'dist directory'
      echo ''
      cd dist
      ls -a
      echo ''
    displayName: list repository files

  - script: |
      echo 'success'
      echo 'azureSubscription: $(azureSubscription)'
      echo 'azureStorageName: $(azureStorageName)'
    displayName: test condition to Copy files to Azure Blob storage
    condition: |
      and(
        ne(variables.azureSubscription, ''),
        ne(variables.azureStorageName, '')
      )
  # - task: AzureCLI@2
  #   displayName: Copy files to Azure Blob storage
  #   condition: |
  #     and(
  #       ne(variables.azureSubscription, ''),
  #       ne(variables.azureStorageName, '')
  #     )
  #   inputs:
  #     azureSubscription: $(azureSubscription)
  #     scriptType: ps
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       az storage blob upload-batch -s "$(System.DefaultWorkingDirectory)/dist" -d \$web --account-name "$(azureStorageName)"

  - script: |
      echo 'success'
      echo 'azureSubscription: $(azureSubscription)'
      echo 'azureCdnResouseGroup: $(azureCdnResouseGroup)'
      echo 'azureCdnName: $(azureCdnName)'
      echo 'azureCdnProfileName: $(azureCdnProfileName)'
    displayName: test condition to Purge Azure CDN
    condition: |
      and(
        ne(variables.azureSubscription, ''),
        ne(variables.azureCdnResouseGroup, ''),
        ne(variables.azureCdnName, ''),
        ne(variables.azureCdnProfileName, '')
      )
  # - task: AzureCLI@2
  #   displayName: Purge Azure CDN
  #   condition: |
  #     and(
  #       ne(variables.azureSubscription, ''),
  #       ne(variables.azureCdnResouseGroup, ''),
  #       ne(variables.azureCdnName, ''),
  #       ne(variables.azureCdnProfileName, '')
  #     )
  #   inputs:
  #     azureSubscription: $(azureSubscription)
  #     scriptType: ps
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       az cdn endpoint purge --resource-group $(azureCdnResouseGroup) --name $(azureCdnName) --profile-name $(azureCdnProfileName) --content-paths "/*"
