# Template types & usage
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
#
# Azure CLI task
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops
#
# deploy a static web site to the MS Azure Cloud Storage and CDN
#
parameters:
  - name: azureSubscription
    type: string
    default: ''
  - name: azureStorageName
    type: string
    default: ''
  - name: azureCdnResouseGroup
    type: string
    default: ''
  - name: azureCdnName
    type: string
    default: ''
  - name: azureCdnProfileName
    type: string
    default: ''

steps:
  - checkout: self
    clean: true
  - script: ls
    displayName: list files

  - script: echo 'success'
    displayName: condition has Azure Subscription
    condition: ne(parameters.azureSubscription, '')

  - script: echo 'success'
    displayName: condition to update Azure Storage
    condition: |
      and(
        ne(parameters.azureSubscription, ''),
        ne(parameters.azureStorageName, '')
      )

  - script: echo 'success'
    displayName: condition to update Azure CDN
    condition: |
      and(
        ne(parameters.azureSubscription, ''),
        ne(parameters.azureCdnResouseGroup, ''),
        ne(parameters.azureCdnName, ''),
        ne(parameters.azureCdnProfileName, '')
      )
