# Template types & usage
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops
#
# Use a template parameter as part of a condition
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#use-a-template-parameter-as-part-of-a-condition
#
# Azure CLI task
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-cli?view=azure-devops
#
# deploy a static web site to the MS Azure Cloud Storage and CDN
#
parameters:
  - name: azureSubscription
    type: string
    default: ''
  - name: azureStorageName
    type: string
    default: ''
  - name: azureCdnResouseGroup
    type: string
    default: ''
  - name: azureCdnName
    type: string
    default: ''
  - name: azureCdnProfileName
    type: string
    default: ''

steps:
  - checkout: self
    clean: true
  - script: ls
    displayName: list files

  - script: |
      echo 'azureSubscription: $(azureSubscription)'
      echo 'azureStorageName: $(azureStorageName)'
      echo 'azureCdnResouseGroup: $(azureCdnResouseGroup)'
      echo 'azureCdnName: $(azureCdnName)'
      echo 'azureCdnProfileName: $(azureCdnProfileName)'
    displayName: show variables from the library

  - script: |
      echo 'success'
      echo 'azureSubscription: ${{ parameters.azureSubscription }}'
      echo 'azureStorageName: ${{ parameters.azureStorageName }}'
    displayName: test condition to Copy files to Azure Blob storage
    condition: |
      and(
        ne('${{ parameters.azureSubscription }}', ''),
        ne('${{ parameters.azureStorageName }}', '')
      )
  # - task: AzureCLI@2
  #   displayName: Copy files to Azure Blob storage
  #   condition: |
  #     and(
  #       ne('${{ parameters.azureSubscription }}', ''),
  #       ne('${{ parameters.azureStorageName }}', '')
  #     )
  #   inputs:
  #     azureSubscription: ${{ parameters.azureSubscription }}
  #     scriptType: ps
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       az storage blob upload-batch -s "$(System.DefaultWorkingDirectory)/dist" -d \$web --account-name "${{ parameters.azureStorageName }}"

  - script: |
      echo 'success'
      echo 'azureSubscription: ${{ parameters.azureSubscription }}'
      echo 'azureCdnResouseGroup: ${{ parameters.azureCdnResouseGroup }}'
      echo 'azureCdnName: ${{ parameters.azureCdnName }}'
      echo 'azureCdnProfileName: ${{ parameters.azureCdnProfileName }}'
    displayName: test condition to Purge Azure CDN
    condition: |
      and(
        ne('${{ parameters.azureSubscription }}', ''),
        ne('${{ parameters.azureCdnResouseGroup }}', ''),
        ne('${{ parameters.azureCdnName }}', ''),
        ne('${{ parameters.azureCdnProfileName }}', '')
      )
  # - task: AzureCLI@2
  #   displayName: Purge Azure CDN
  #   condition: |
  #     and(
  #       ne('${{ parameters.azureSubscription }}', ''),
  #       ne('${{ parameters.azureCdnResouseGroup }}', ''),
  #       ne('${{ parameters.azureCdnName }}', ''),
  #       ne('${{ parameters.azureCdnProfileName }}', '')
  #     )
  #   inputs:
  #     azureSubscription: ${{ parameters.azureSubscription }}
  #     scriptType: ps
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       az cdn endpoint purge --resource-group ${{ parameters.azureCdnResouseGroup }} --name ${{ parameters.azureCdnName }} --profile-name ${{ parameters.azureCdnProfileName }} --content-paths "/*"
