# pipeline suggested name: CD DEV frontend-app-2
# pipeline to deploy the application to the server

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - build/dev/frontend-app-2

pr: none

variables:
  - group: cd-vars_common
  - group: cd-vars_dev_frontend-app-2

steps:
  - template: templates/deploy-one.yml
