# pipeline suggested name: CD frontend-app-2 DEV
# pipeline to deploy the application to the server

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - build/dev/frontend-app-2

pr: none

variables:
  - group: cd-vars_dev_frontend-app-2

jobs:
  - template: templates/deploy-one.yml
