# name: CI branches
# this pipeline validates and generate the builds for master or develop branch
trigger:
  batch: true
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
      - .azure-pipelines/*
      - .vscode/*
      - docs/*
      - tools/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    ENV: 'prod'
  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    ENV: 'dev'

stages:
  - stage: validate_build
    displayName: validate and build
    jobs:
      - job: initial_setup
        displayName: nx calculate commands
        steps:
          - template: templates/steps_install-node-modules.yml
          - script: |
              echo "##vso[task.setvariable variable=COMMANDS;isOutput=true]$(node ./tools/scripts/nx-calculate-commands.js false)"
            name: setCommands
          - script: echo $(setCommands.COMMANDS)
            name: echoCommands

      - job: lint
        displayName: lint projects
        dependsOn: initial_setup
        condition: |
          and(
            succeeded(),
            not(
              contains(
                dependencies.initial_setup.outputs['setCommands.COMMANDS'],
                '"lint":[]'
              )
            )
          )
        variables:
          COMMANDS: $[ dependencies.initial_setup.outputs['setCommands.COMMANDS'] ]
        steps:
          - template: templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-many.js '$(COMMANDS)' lint
            displayName: running lint

      - job: test
        displayName: test projects
        dependsOn: initial_setup
        condition: |
          and(
            succeeded(),
            not(
              contains(
                dependencies.initial_setup.outputs['setCommands.COMMANDS'],
                '"test":[]'
              )
            )
          )
        variables:
          COMMANDS: $[ dependencies.initial_setup.outputs['setCommands.COMMANDS'] ]
        steps:
          - template: templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-many.js '$(COMMANDS)' test
            displayName: running tests

      - job: build
        displayName: build projects
        dependsOn: initial_setup
        condition: |
          and(
            succeeded(),
            not(
              contains(
                dependencies.initial_setup.outputs['setCommands.COMMANDS'],
                '"build":[]'
              )
            )
          )
        variables:
          COMMANDS: $[ dependencies.initial_setup.outputs['setCommands.COMMANDS'] ]
        steps:
          - template: templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/nx-run-many.js '$(COMMANDS)' build $(ENV)
            displayName: running builds
          - publish: $(System.DefaultWorkingDirectory)/dist/apps
            artifact: apps

      - job: failure
        displayName: fail if there is no build
        dependsOn: initial_setup
        condition: |
          contains(
            dependencies.initial_setup.outputs['setCommands.COMMANDS'],
            '"build":[]'
          )
        steps:
          - script: |
              echo "##vso[task.complete result=Failed;]DONE"
              exit 1
            displayName: trigger the failure


  - stage: git_push
    displayName: git push
    dependsOn: validate_build
    condition: succeeded()
    jobs:
      - job: push_all
        displayName: push the builded apps
        steps:
          - script: echo $(Pipeline.Resources.current)
          - download: current
            artifact: apps
          - script: |
              cd $(Pipeline.Workspace)/apps
              ls
            displayName: list apps available on $(Pipeline.Workspace)/apps
          - template: templates/steps_install-node-modules.yml
          - script: node ./tools/scripts/git-push-builds-to-branches.js $(Pipeline.Workspace)/apps $(ENV)
            displayName: running git push