# example of how share values between stages using a var
#
trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: stage_1
    displayName: first
    jobs:
      - job: setGreetingsVar
        steps:
          - checkout: none
          - script: |
              echo "##vso[task.setvariable variable=greetings;isOutput=true]'hello world'"
            name: customVariables
            displayName: set customVariables.greetings value
          - script: echo $(customVariables.greetings)
            displayName: display customVariables.greetings value

  - stage: stage_2
    displayName: second
    dependsOn: stage_1
    condition: succeeded()
    jobs:
      - job: readGlobalVar
        variables:
          greetings: $[ dependencies.stage_1.output['setGreetingsVar.customVariables.greetings'] ]
        steps:
          - checkout: none
          - script: echo $(greetings)
            displayName: greetings var value from the stage_1
