# example of how share values between stages using a global var
#
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  globalVar: 'initial value'

stages:
  - stage: 1
    displayName: first
    jobs:
      - job: setGlobalVar
        steps:
          - script: echo $(globalVar)
            displayName: echo $(globalVar)
          - script: |
              echo "##vso[task.setvariable variable=globalVar;]'value from the stage 1 job setGlobalVar'"
            displayName: update $(globalVar) value

  - stage: 2
    displayName: second
    jobs:
      - job: readGlobalVar
        steps:
          - script: echo $(globalVar)
            displayName: echo $(globalVar)
